Move remaining network calls to injected script
wikimedia/readinglists-extension-safari pull request #7
Opened 2018-06-04 16:28 UTC by mdholloway

We can't omit cookies in the i18n message fetch calls because this means
disregarding the user's language preferences. But sending them from the
popup script results in Safari ending the session (at least on some
machines...).  This moves the i18n message fetches over to the injected
script, so that the session cookie issue is resolved once and for all.

2018-06-04 16:28 UTC, mdholloway commented
Note: I haven't fully tested this yet, but it seems to work well for the 'success' and 'show login' cases.

2018-06-04 17:33 UTC, berndsi commented
@mdholloway I changed my macOS language preferences to German, followed by English but still see only English strings in the extension popup used.

2018-06-04 19:07 UTC, mdholloway commented
@berndsi It's the user's language preference as set on-wiki that this respects.  I just checked this by setting my preferred language to German and saving a page on enwiki, and it worked: I received the German translation.

2018-06-04 19:07 UTC, mdholloway commented
Oops, my click went a little off the mark.

2018-06-04 19:43 UTC, berndsi commented
@mdholloway Thanks! With the correct preference change it works! Nice!

2018-06-04 19:47 UTC, berndsi requested changes
Have you considered keeping the i18n functions together but in a separate js file? I think they naturally belong together.

2018-06-04 19:47 UTC, berndsi commented on WikipediaReadingLists.safariextension/injected.js
> +// XXX: Keep in sync with popup.js
You probably meant to change the XXX to something else.

2018-06-04 19:47 UTC, berndsi commented on WikipediaReadingLists.safariextension/popup.js
> +// XXX: Keep in sync with injected.js
Same as above

2018-06-04 20:07 UTC, mdholloway commented
FWIW I was using 'XXX' in the sense described here: https://softwareengineering.stackexchange.com/questions/65467/what-does-xxx-mean-in-a-comment

Probably could be a 'FIXME', though.

2018-06-04 20:31 UTC, berndsi commented
@mdholloway Ah, ok. Thanks for the link. What do you think about the other suggestion?

2018-06-05 10:16 UTC, tgr approved these changes

2018-06-05 14:28 UTC, mdholloway commented
@berndsi Can we kick code organization out to a new issue? We really need to 
- define a browser support policy ([MediaWiki's](https://www.mediawiki.org/wiki/Compatibility#Browsers) is probably too conservative),
- determine what import methods are supported for the set of browsers we want to support,
- then actually get it working. 

FWIW I did some experimenting with ES6 modules when I first started writing the Chrome extension, but put it aside in the interest of time.

2018-06-05 15:02 UTC, berndsi commented
@mdholloway Yes, that could come later. It looked just weird that the i18n functions were sprinkled throughout the other code. I would have preferred to have them appear somewhat together in the code.

2018-06-05 15:02 UTC, berndsi approved these changes

2018-06-05 15:06 UTC, merged